module bd_top #(
    parameter logic SIM_EN = 0
) (
    inout [14:0] DDR_0_addr,
    inout [ 2:0] DDR_0_ba,
    inout        DDR_0_cas_n,
    inout        DDR_0_ck_n,
    inout        DDR_0_ck_p,
    inout        DDR_0_cke,
    inout        DDR_0_cs_n,
    inout [ 3:0] DDR_0_dm,
    inout [31:0] DDR_0_dq,
    inout [ 3:0] DDR_0_dqs_n,
    inout [ 3:0] DDR_0_dqs_p,
    inout        DDR_0_odt,
    inout        DDR_0_ras_n,
    inout        DDR_0_reset_n,
    inout        DDR_0_we_n,
    inout        FIXED_IO_0_ddr_vrn,
    inout        FIXED_IO_0_ddr_vrp,
    inout [53:0] FIXED_IO_0_mio,
    inout        FIXED_IO_0_ps_clk,
    inout        FIXED_IO_0_ps_porb,
    inout        FIXED_IO_0_ps_srstb,

    input logic s2mm_irq_i,
    input logic mm2s_irq_i,

    output logic ps_clk_o,
    output logic ps_arstn_o,

    axil_if.master m_axil,

    axi_if.slave s_axi
);

    if (SIM_EN) begin : g_axi_mem
        axi_mem i_axi_mem (.s_axi(s_axi));
        axil_master i_axil_master (.m_axil(m_axil));
    end else begin : g_bd
        zynq_bd zynq_bd_i (
            .M00_AXI_0_araddr (m_axil.araddr),
            .M00_AXI_0_arprot (m_axil.arprot),
            .M00_AXI_0_arready(m_axil.arready),
            .M00_AXI_0_arvalid(m_axil.arvalid),
            .M00_AXI_0_awaddr (m_axil.awaddr),
            .M00_AXI_0_awprot (m_axil.awprot),
            .M00_AXI_0_awready(m_axil.awready),
            .M00_AXI_0_awvalid(m_axil.awvalid),
            .M00_AXI_0_bready (m_axil.bready),
            .M00_AXI_0_bresp  (m_axil.bresp),
            .M00_AXI_0_bvalid (m_axil.bvalid),
            .M00_AXI_0_rdata  (m_axil.rdata),
            .M00_AXI_0_rready (m_axil.rready),
            .M00_AXI_0_rresp  (m_axil.rresp),
            .M00_AXI_0_rvalid (m_axil.rvalid),
            .M00_AXI_0_wdata  (m_axil.wdata),
            .M00_AXI_0_wready (m_axil.wready),
            .M00_AXI_0_wstrb  (m_axil.wstrb),
            .M00_AXI_0_wvalid (m_axil.wvalid),

            .S_AXI_HP0_0_araddr (s_axi.araddr),
            .S_AXI_HP0_0_arburst(s_axi.arburst),
            .S_AXI_HP0_0_arcache(s_axi.arcache),
            .S_AXI_HP0_0_arid   ('0),
            .S_AXI_HP0_0_arlen  (s_axi.arlen),
            .S_AXI_HP0_0_arlock (s_axi.arlock),
            .S_AXI_HP0_0_arprot (s_axi.arprot),
            .S_AXI_HP0_0_arqos  (s_axi.arqos),
            .S_AXI_HP0_0_arready(s_axi.arready),
            .S_AXI_HP0_0_arsize (s_axi.arsize),
            .S_AXI_HP0_0_arvalid(s_axi.arvalid),
            .S_AXI_HP0_0_awaddr (s_axi.awaddr),
            .S_AXI_HP0_0_awburst(s_axi.awburst),
            .S_AXI_HP0_0_awcache(s_axi.awcache),
            .S_AXI_HP0_0_awid   ('0),
            .S_AXI_HP0_0_awlen  (s_axi.awlen),
            .S_AXI_HP0_0_awlock (s_axi.awlock),
            .S_AXI_HP0_0_awprot (s_axi.awprot),
            .S_AXI_HP0_0_awqos  (s_axi.awqos),
            .S_AXI_HP0_0_awready(s_axi.awready),
            .S_AXI_HP0_0_awsize (s_axi.awsize),
            .S_AXI_HP0_0_awvalid(s_axi.awvalid),
            .S_AXI_HP0_0_bid    (),
            .S_AXI_HP0_0_bready (s_axi.bready),
            .S_AXI_HP0_0_bresp  (s_axi.bresp),
            .S_AXI_HP0_0_bvalid (s_axi.bvalid),
            .S_AXI_HP0_0_rdata  (s_axi.rdata),
            .S_AXI_HP0_0_rid    ('0),
            .S_AXI_HP0_0_rlast  (s_axi.rlast),
            .S_AXI_HP0_0_rready (s_axi.rready),
            .S_AXI_HP0_0_rresp  (s_axi.rresp),
            .S_AXI_HP0_0_rvalid (s_axi.rvalid),
            .S_AXI_HP0_0_wdata  (s_axi.wdata),
            .S_AXI_HP0_0_wid    ('0),
            .S_AXI_HP0_0_wlast  (s_axi.wlast),
            .S_AXI_HP0_0_wready (s_axi.wready),
            .S_AXI_HP0_0_wstrb  (s_axi.wstrb),
            .S_AXI_HP0_0_wvalid (s_axi.wvalid),

            .DDR_0_addr          (DDR_0_addr),
            .DDR_0_ba            (DDR_0_ba),
            .DDR_0_cas_n         (DDR_0_cas_n),
            .DDR_0_ck_n          (DDR_0_ck_n),
            .DDR_0_ck_p          (DDR_0_ck_p),
            .DDR_0_cke           (DDR_0_cke),
            .DDR_0_cs_n          (DDR_0_cs_n),
            .DDR_0_dm            (DDR_0_dm),
            .DDR_0_dq            (DDR_0_dq),
            .DDR_0_dqs_n         (DDR_0_dqs_n),
            .DDR_0_dqs_p         (DDR_0_dqs_p),
            .DDR_0_odt           (DDR_0_odt),
            .DDR_0_ras_n         (DDR_0_ras_n),
            .DDR_0_reset_n       (DDR_0_reset_n),
            .DDR_0_we_n          (DDR_0_we_n),
            .FCLK_CLK0_0         (ps_clk_o),
            .FIXED_IO_0_ddr_vrn  (FIXED_IO_0_ddr_vrn),
            .FIXED_IO_0_ddr_vrp  (FIXED_IO_0_ddr_vrp),
            .FIXED_IO_0_mio      (FIXED_IO_0_mio),
            .FIXED_IO_0_ps_clk   (FIXED_IO_0_ps_clk),
            .FIXED_IO_0_ps_porb  (FIXED_IO_0_ps_porb),
            .FIXED_IO_0_ps_srstb (FIXED_IO_0_ps_srstb),
            .peripheral_aresetn_0(ps_arstn_o),
            .s2mm_irq            (s2mm_irq_i),
            .mm2s_irq            (mm2s_irq_i)
        );
    end

endmodule
